//
// Created by TianyaoChu on 2023/5/11.
//

#ifndef QUANTUM_NETWORKS_ENTANGLE_PARAMS_H
#define QUANTUM_NETWORKS_ENTANGLE_PARAMS_H

const int LIFESPAN = 10000;

#endif //QUANTUM_NETWORKS_ENTANGLE_PARAMS_H
